name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # This runs every hour
  workflow_dispatch:  # This lets you run it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/fmhy/edit.git
          git fetch upstream
          git checkout main
          git rebase upstream/main
          git push origin main --force
